dist: xenial
os: linux
language: java
jdk:
- openjdk10
- openjdk8
env:
jobs:
  include:
  - stage: Test
    script: "./gradlew test"
  - stage: Build
    script: "./gradlew build"
  - stage: Deploy
    deploy:
      provider: heroku
      api_key:
        secure: ABqaHwIf6Fejb/02mBzpRSciyWeL+z29/1d2AygKruXvvQgL9OSWvkXj3QIKZ3JUwBcg0WgX0AFnH+TlOCmGmddPjrU/LCC+qTadPe0IFv1149EduNe1bv+1zI1oaIFqAARi5Lkik/6+Kxpie3SGIkv7ASuC+UnquEqO25NHPUDfTI5KGfrEC2oyJwO7TNLlm1gjB11muxgqrK6MqUqpnkel82DGgR5v+3fkFuz72+mzbLAs3NSoAYVe9hxjzG18xaaYb+uXMmN1OXPIrKGe725N6PdQObLQtfSMRWdNo2sbZk7ammBZ2zVZ5SS9uirZUJW1jsoq7tqfc/olPsnOYo/YJtSMfqlWzuBS6tgW9W9ncNr84hg23E9zeC7t/PsOFgL1VLYOqAPmQklMDwMtCN/kOruZBlB0zmXabdQmVSFhg305GueUmKv0olHNYZ4u2z1e+ZlEqHGRWdH22iRCgk5tMpTdi6Uk17qeU2S+ieMlGpIJGCcpDhOMNO834SasMDFAXNZNeMWkJB44+2AY6MMl4c2aPgp0FIb3W1lYlyoY71yapGXlBbzefH5SsqcI0TXPKIddh9TW1ck0DCCRt+i87z+shJJ2esiehCGTBaNtlQnPRThwhSUunlNvEa17h4eQPzBsDVx2Y2OsvYV5eBnKsF6lRStSW5nUoopGOh8=
      app: ci-me-please-brayaon
      on: main
