dist: xenial
os: linux
language: java
jdk:
- openjdk10
- openjdk8
notifications:
  slack:
  - rooms:
    - secure: IoJyCcVJPU4RYDCLb14vSfJs6AazAIxdYTkMD7OZ5QRCR/rNxyoZY/UjZ+Dmss2jqN5tpK7eh7/V+hoLBnqairVjfL+Cjdksh7mpoi1xNPdJUlZ4xAdRrv6BIsv828YyO8GEAyFHKaNK+pTQyljHv0UDbfO3YjmZqun7lt4TuiScjcaiPwqPbdO7jj4+DX7mCHnY6LoloLwOMQdCdhPPYIKfLxXBxtli+9mnF6DniW21N6poI97T9kE2xzjJBRdaSNvxQgfowQInCq4dm7F+RAal4ZdHeFz4WaYApqXzzMLHodaxQYQim0aqj+5iIO5E0jYlpdpEoegvKYJdUpMoaaxnGVmTazOVbJX15k7iecF0yFB6c10Dtni20cJRq7LyUnk54fXEI+mqxtubaKdzfU0a6imP8ppWm1LdcrBLS6m1R50ekESXriW9CYfFHfAuQQu+bfz4rlVFw3Ttb9UmvBZs4Z8cWTSX8m++qoYHOx7His/6wcwR8tBX2PH5qMne/y/HyI9g6kprJWRICFqJ9jBbm5QcEk/5COurUyuuu6nN8bfc1eXzPG7eV/XB1ZkNYrdN2vlHFlc7bc8NAHj3ckU3+MCsSgu9Kc5H/cS00MxWgHBZvdi8o7V8vJ3bzyWk7O2sX5Lg7ck/otQe5GU5kZguxjIRIGHMMOh8IPCQ71w=
    on_success: always
    on_failure: always
jobs:
  include:
  - stage: Test
    script: "./gradlew test"
  - stage: Build
    script: "./gradlew build"
  - stage: Deploy
    deploy:
      provider: heroku
      api_key:
        secure: 0Tn75iEg33AWE2rkTJmzLHKgwCdY405wkvnJleg3SR72k+xLR2NyckHf2Hr4nV5e9PmgwdzZt6GssjMQ9rdCmk0hME6qSzE+xk+orTDsV1wU8isZVA8N9ust2rYoBbaBBKjjgcz+8vAJv5fo2B+clrgROOSw8C3t82YjDuviFNo3LE6kNUmt5ZH/wKAa0SE3tkWDPj5nDACZ8yMfarg1S8CY44ZHB9EzDmOMQUekO0LKsQZBAmm0trYSqStEI5R2UpvPYhH6r/ZLchxyYikcCCmr7BsXZ8wbCLxMU5++DTHEL3kvoP5Bm0U3F2cjG0uUQsMBORvwqv/DrSPJ+RqRr4EYmfqcNQ9kf9ffJUfjTWlHhZEwzUzBTaArMJ6XiaNK9ki2MGUN6EfanVKRHbd/wytP95ptamoci6JM4aUYDNsJCeOWFuTPVHhCGMQDGLFsXoBg/JFIIa50s2XHVeX3SPzXQlHoMx1njOLxr2qer1P03a4GM0JySJZBIiOlWmWdrt3OO1d3mriknsCkmGSzZBOBiYr5Zm7MC2R9ddDhBK87g0zvyGY++ETVB6RRTxiXp1J2PACU7mAUlr33ZHbbt1lC9OmmE1sAUsyhS3+lQoYPjMZ4hFCd7O83jfJA9N6JKCvhILC1sSP6VCiuKzvtD43Bzl0LWRiMpml3QLpYcuY=
      app: ci-me-please-brayaon
      on: main