dist: xenial
os: linux
language: java
jdk:
- openjdk10
- openjdk8

notifications:
  slack:
    rooms:
      secure: IoJyCcVJPU4RYDCLb14vSfJs6AazAIxdYTkMD7OZ5QRCR/rNxyoZY/UjZ+Dmss2jqN5tpK7eh7/V+hoLBnqairVjfL+Cjdksh7mpoi1xNPdJUlZ4xAdRrv6BIsv828YyO8GEAyFHKaNK+pTQyljHv0UDbfO3YjmZqun7lt4TuiScjcaiPwqPbdO7jj4+DX7mCHnY6LoloLwOMQdCdhPPYIKfLxXBxtli+9mnF6DniW21N6poI97T9kE2xzjJBRdaSNvxQgfowQInCq4dm7F+RAal4ZdHeFz4WaYApqXzzMLHodaxQYQim0aqj+5iIO5E0jYlpdpEoegvKYJdUpMoaaxnGVmTazOVbJX15k7iecF0yFB6c10Dtni20cJRq7LyUnk54fXEI+mqxtubaKdzfU0a6imP8ppWm1LdcrBLS6m1R50ekESXriW9CYfFHfAuQQu+bfz4rlVFw3Ttb9UmvBZs4Z8cWTSX8m++qoYHOx7His/6wcwR8tBX2PH5qMne/y/HyI9g6kprJWRICFqJ9jBbm5QcEk/5COurUyuuu6nN8bfc1eXzPG7eV/XB1ZkNYrdN2vlHFlc7bc8NAHj3ckU3+MCsSgu9Kc5H/cS00MxWgHBZvdi8o7V8vJ3bzyWk7O2sX5Lg7ck/otQe5GU5kZguxjIRIGHMMOh8IPCQ71w=
    on_success: always
    on_failure: always

jobs:
  include:
  - stage: Test
    script: "./gradlew test"
  - stage: Build
    script: "./gradlew build"
  - stage: Deploy
    deploy:
      provider: heroku
      api_key:
        secure: g3CEhksv07DXOXNxkkBk48Bs7z0Gwp2ib+NsMOWdKkcDgf7ebYsbp6gXr6H4IkHG8nvRc3hDt4NRTcmwnL0JThOZKgEgyDqMgiKIzZ0xfLT44+6Faf6B4SbERewK/xvCkhvgFy346v9ShGUyYsrddHK1rMK5ept9ZefMVT6Hr2zmPmoGPAeai3aEgz1tbas/FLqE+4nt00uaekneorVygsrsIFqvnEhD1f205nmOtToGCXJiUxIStilWDiEx94DSVQ20iW9B0d17a1o3pRfjfHVDq2swACb2kSWWcWrY1TRP41DotcSRzXpDwahkSUp+llW/0BJakSrWBRHZ4T2Xayc4LeneTNY8OZ01VkPaBQMIjJIspeNa+grfCB1qHAs7x+V1M53I0lrbD3HQOSx6nxTYjlBMvdKZ6rjvrfZUcaAxtw0FFfGiawqyApr+wnUiIXHNgZIq2tzE55BWKlb9UyOuGnQXGLyCRp327CoTpo4DIP7LPe+kDt7idvqzLSPQKnZQIKOiYf7GdR32iGmHQDo5K3oVI70RquWoI2pjaj1xwVp6guZ7BhJtawlw6ZwNp0o7ahqCDerBW/lxOsrg8RdYJ/jD7TjIyhPRZvxj2uONnutSFLrn3NabnKnVqQWukPNbXjv3swdcPa8ooaOkrxETY1MNDbxxI2nBIJqmc9Y=
      app: ci-me-please-brayaon
      on: main