dist: xenial
os: linux
language: java
jdk:
- openjdk10
- openjdk8
notifications:
  slack: 
    rooms: praxisunal:yAxYwLHSyRC9Zi8uMckokqQW
    on_success: always
    on_failure: always
jobs:
  include:
  - stage: Test
    script: "./gradlew test"
  - stage: Build
    script: "./gradlew build"
  - stage: Deploy
    deploy:
      provider: heroku
      api_key: $HEROKU_API_KEY
      app: ci-me-please-brayaon
      skip_cleanup: true
      on: main